# Generated by Django 4.1 on 2022-11-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("cidade", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=100)),
                ("caractetistica", models.TextField()),
            ],
        ),
    ]
