# Generated by Django 4.1 on 2022-11-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0002_empresa_nicho"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tecnologia", models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name="empresa",
            name="logo",
            field=models.ImageField(null=True, upload_to="logo_empresa"),
        ),
        migrations.AddField(
            model_name="empresa",
            name="tecnologias",
            field=models.ManyToManyField(to="empresa.tecnologia"),
        ),
    ]
