# Generated by Django 4.1 on 2022-11-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0004_vagas"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Vagas",
            new_name="Vaga",
        ),
    ]
