# Generated by Django 4.1 on 2022-11-10 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0006_rename_caractetistica_empresa_caracteristica"),
    ]

    operations = [
        migrations.RenameField(
            model_name="empresa",
            old_name="caracteristica",
            new_name="caracteristicas",
        ),
        migrations.AlterField(
            model_name="vaga",
            name="empresa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="empresa.empresa",
            ),
        ),
    ]
