# Generated by Django 4.1 on 2022-11-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0008_alter_empresa_caracteristicas"),
    ]

    operations = [
        migrations.AddField(
            model_name="vaga",
            name="email",
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
